---
- name: copy artifact.tar.gz into ubuntu backend
  become: yes
  copy:
      src: /root/project/artifact.tar.gz
      dest: /home/ubuntu/backend/artifact.tar.gz
      force: yes

- name: unzip backend
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
    ls -la

- name: start npm
  become: yes
  shell: |
        cd /home/ubuntu/backend
        npm install
        npm run build 
        cat .env
        pm2 stop default
        pm2 start npm -- start

- name: start pm2
  become: yes
  shell: |
        cd /home/ubuntu/backend
        pm2 stop default
        pm2 start npm -- start
        cd dist
        pm2 start main.js