---
- name: Extract foo.tgz into /var/lib/foo
  unarchive:
      src: ./artifact.tar.gz
      dest: ~/
- name: start node
  shell: |
        npm install
        pm2 stop default
        pm2 start npm -- start