---
- name: Extract artifact.tar.gz into ~/
  become: yes
  unarchive:
      src: /root/project/artifact.tar.gz
      dest: /
- name: start node
  become: yes
  shell: |
        cd /
        npm install
        pm2 stop default
        pm2 start npm -- start